---
production:
  delivery_method: :smtp
  smtp_settings:
    smtpid: "smtp.gmail.com"
    smtport: 587
    domain: example.net
    authentication: :login
    senderid: "palak.jain@infobeans.com"
    password: "xyz"
    receiverid: "aaryaa.bhosale@infobeans.com"